spring.application.name=mrcustomeradapter

server.port=8081

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/mini_retail
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Tampilkan error detail
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# Logging level
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.level.org.springframework.r2dbc=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

